name: FrontendTest 🧪
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
     
      - name: Cypress run
        uses: cypress-io/github-action@v2        
         with:
          # browser: chrome
           spec: cypress/integration/lolTests/home.spec.js
         
    
